// Package completion supplies Bash completion without executing remote actions.
package completion

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/LittleDrongo/deployctl/internal/config"
	"github.com/LittleDrongo/deployctl/internal/project"
)

const Bash = `# Generated by deployctl completion bash.
_deployctl_complete() {
    local item
    COMPREPLY=()
    while IFS= read -r item; do
        [[ -z "$item" ]] || COMPREPLY+=("$item")
    done < <("${COMP_WORDS[0]}" __complete "${COMP_WORDS[@]:1:COMP_CWORD}" 2>/dev/null)
}
complete -o default -F _deployctl_complete deployctl deployctl.exe
`

func Run(args []string, out io.Writer) error {
	if len(args) == 1 && args[0] == "bash" {
		_, err := io.WriteString(out, Bash)
		return err
	}
	if len(args) == 1 && (args[0] == "--help" || args[0] == "-h") {
		_, err := fmt.Fprintln(out, "deployctl completion bash | deployctl completion install bash")
		return err
	}
	if len(args) != 2 || args[0] != "install" || args[1] != "bash" {
		return fmt.Errorf("usage: deployctl completion bash | deployctl completion install bash")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	base := os.Getenv("XDG_DATA_HOME")
	if base == "" {
		base = filepath.Join(home, ".local", "share")
	}
	if !filepath.IsAbs(base) {
		return fmt.Errorf("XDG_DATA_HOME must be absolute")
	}
	dest := filepath.Join(base, "bash-completion", "completions", "deployctl")
	if st, err := os.Lstat(dest); err == nil {
		if !st.Mode().IsRegular() {
			return fmt.Errorf("completion path must be a regular file: %s", dest)
		}
		data, err := os.ReadFile(dest)
		if err != nil {
			return err
		}
		if !strings.HasPrefix(string(data), "# Generated by deployctl completion bash.\n") {
			return fmt.Errorf("refusing to overwrite an unrelated completion file: %s", dest)
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(dest, []byte(Bash), 0644); err != nil {
		return err
	}
	_, err = fmt.Fprintf(out, "Автодополнение Bash установлено: %s\nС bash-completion оно загрузится в новых сеансах автоматически.\nДля текущего терминала выполните: source '%s'\n", dest, strings.ReplaceAll(dest, "'", "'\"'\"'"))
	return err
}

var commands = strings.Fields("build clean completion config doctor help info init logs release remove restart status stop up version")
var flags = map[string]string{
	"build":   "--root --config --package --platform --tag --timeout --dry-run --help",
	"init":    "--root --config --scaffold --makefile --dry-run --help",
	"up":      "--root --config --package --tag --timeout --keep-artifact --dry-run --help",
	"logs":    "--root --config --tail --follow -f --dry-run --help",
	"doctor":  "--root --config --dry-run --help",
	"status":  "--root --config --dry-run --help",
	"stop":    "--root --config --dry-run --help",
	"restart": "--root --config --dry-run --help",
	"remove":  "--root --config --dry-run --help",
	"config":  "--root --config --help",
	"info":    "--root --json --help",
	"release": "--root --dry-run --help",
	"clean":   "--root --dry-run --help",
}

func Complete(words []string, out io.Writer) error {
	if len(words) == 0 {
		words = []string{""}
	}
	current := words[len(words)-1]
	before := words[:len(words)-1]
	candidates := []string{}
	if len(before) == 0 {
		candidates = commands
	} else {
		action := before[0]
		root, filename, pending := "", "", ""
		positionals := 0
		for _, word := range before[1:] {
			if pending != "" {
				if pending == "--root" {
					root = word
				}
				if pending == "--config" {
					filename = word
				}
				pending = ""
				continue
			}
			name, value, equals := strings.Cut(word, "=")
			switch name {
			case "--root", "--config", "--package", "--platform", "--tag", "--timeout", "--tail":
				if equals {
					if name == "--root" {
						root = value
					}
					if name == "--config" {
						filename = value
					}
				} else {
					pending = name
				}
			default:
				if !strings.HasPrefix(word, "-") {
					positionals++
				}
			}
		}
		if pending == "--platform" || strings.HasPrefix(current, "--platform=") {
			candidates = strings.Fields("windows-amd64 windows-arm64 linux-amd64 linux-arm64 android-arm64 windows-386 linux-386 darwin-amd64 darwin-arm64")
			if strings.HasPrefix(current, "--platform=") {
				for i := range candidates {
					candidates[i] = "--platform=" + candidates[i]
				}
			}
		} else if pending != "" {
			// Let Bash perform normal file completion for paths; never invoke builds or SSH.
		} else if strings.HasPrefix(current, "-") {
			candidates = strings.Fields(flags[action])
		} else if action == "completion" {
			if positionals == 0 {
				candidates = []string{"bash", "install"}
			} else if positionals == 1 && before[len(before)-1] == "install" {
				candidates = []string{"bash"}
			}
		} else if action == "config" && positionals == 0 {
			candidates = []string{"check"}
		} else if positionals == 0 && isRemote(action) {
			cwd, err := os.Getwd()
			if err != nil {
				return nil
			}
			dir, err := project.Root(cwd, root)
			if err != nil {
				return nil
			}
			c, err := config.Load(config.Path(dir, filename))
			if err != nil {
				return nil
			}
			for name := range c.Targets {
				candidates = append(candidates, name)
			}
		}
	}
	sort.Strings(candidates)
	for _, candidate := range candidates {
		if strings.HasPrefix(candidate, current) {
			if _, err := fmt.Fprintln(out, candidate); err != nil {
				return err
			}
		}
	}
	return nil
}

func isRemote(action string) bool {
	switch action {
	case "up", "doctor", "status", "logs", "stop", "restart", "remove":
		return true
	}
	return false
}
